name: Sredictio Deployment Test (Ubuntu)

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    name: Run Sredictio On Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Download NLTK VADER Lexicon
      run: |
        python3 -c "import nltk; nltk.download('vader_lexicon')"
    - name: Run Sredictio
      run: |
        python3 main.py stockHistory.csv Model_LBW-20_NOI-100000.zip "Boeing" BA

